//! Theme drawing: at the prompt hook the engine writes the theme header to the real terminal.
//!
//! Division of labor: the shell renders a multi-line placeholder prompt so that the shell
//! geometry accounts for the header lines. The engine does not parse ANSI from the pty
//! output; it only passes bytes through and positions the cursor:
//! - `prompt_start`: emitted on the `h` announcement, before the shell's multi-line placeholder.
//! - `redraw_header_cfg`: after the placeholder passes through, move up by the header line count
//!   and fill in the real header (line content generated by
//!   [`crate::render::render_header_lines`] from the KDL config), then restore the cursor.
//! - `render_prompt`: overwrite the placeholder with `\r` + prefix. The prefix's visible width
//!   equals the placeholder's, keeping shell redraw column offsets aligned.
//! - `render_header_cfg`: for the instant header only (engine has not spawned the shell yet),
//!   drawing the full header + prefix directly.

use std::io::{self, Write};

/// Information the prompt window needs, parsed from the announcement line
/// (`h\t<exit>\t<cwd>[\t<jobs>][\t<history>][\t<pipestatus>]`).
pub struct HeaderInfo {
    pub exit_code: Option<i32>,
    pub cwd: String,
    /// Duration of the previous command in seconds (timed by the engine: Enter → this precmd); 0 for the first prompt.
    pub exec_seconds: f64,
    pub jobs: usize,
    /// Command number: zsh sends `HISTCMD`, pwsh sends the last history entry's
    /// `HistoryInfo.Id` (also a monotonically increasing session number); bash/fish
    /// have no such column and use 0.
    pub history: usize,
    /// Exit code of every command in the pipeline (`$pipestatus` in zsh/fish,
    /// `$PIPESTATUS` in bash), comma-separated on the wire. Empty when the shell has
    /// none (pwsh). Drives the extended status states, see `prompt_state`.
    pub pipestatus: Vec<i32>,
}

/// git status of the current directory (computed by the p11k-gitstatus API, drawn with the header).
#[derive(Clone)]
pub struct GitStatus {
    /// Local branch name (empty on detached HEAD).
    pub branch: String,
    /// Commit oid of HEAD (p10k `SHOW_CHANGESET` takes its first N digits).
    pub commit: String,
    pub staged: usize,
    pub unstaged: usize,
    pub conflicted: usize,
    pub untracked: usize,
    pub ahead: usize,
    pub behind: usize,
    /// Ahead/behind of the push remote (p10k `VCS_STATUS_PUSH_COMMITS_{AHEAD,BEHIND}`).
    pub push_ahead: usize,
    pub push_behind: usize,
    pub stashes: usize,
    /// Operation in progress (merge/rebase/..., p10k `VCS_STATUS_ACTION`); empty = none.
    pub action: String,
    /// Tag HEAD points at (p10k `VCS_STATUS_TAG`); shown as `#tag` when there is no local branch.
    pub tag: String,
    /// upstream branch name (p10k `VCS_STATUS_REMOTE_BRANCH`); shown as `local:remote`
    /// when it differs from the local branch name.
    pub remote_branch: String,
    /// Title of the last commit (p10k `VCS_STATUS_COMMIT_SUMMARY`): shows the `wip`
    /// marker when it contains wip/WIP.
    pub commit_summary: String,
    /// Number of index entries (p10k `VCS_STATUS_INDEX_SIZE`): comparing it against
    /// `max-index-size-dirty` reveals whether the dirty stats were skipped (when skipped the
    /// unstaged count is unknown and `─` is drawn).
    pub index_size: usize,
    /// tracking remote URL (used to pick the vcs icon by domain, e.g. github/archlinux).
    pub remote_url: String,
}

/// OSC 133 A: prompt start marker (shell integration). Under the placeholder protocol the
/// engine emits it on the `h` announcement (before the shell renders the multi-line
/// placeholder); it is not repeated when the header is filled in or redrawn.
pub fn prompt_start(out: &mut dyn Write) -> io::Result<()> {
    write!(out, "\x1b]133;A\x07")
}

/// Write the header content line by line, advancing to the start of the next line, and return
/// each line's **display width**. When content is wider than the terminal the terminal wraps it,
/// and the caller converts that width into the actual number of rows occupied (the instant
/// header must move up by it to erase).
fn header_body(out: &mut dyn Write, lines: &[String]) -> io::Result<Vec<usize>> {
    let mut widths = Vec::with_capacity(lines.len());
    for line in lines {
        write!(out, "\r\x1b[K")?;
        out.write_all(line.as_bytes())?;
        write!(out, "\r\n")?;
        widths.push(crate::render::display_width_of(line));
    }
    Ok(widths)
}

/// Render the full header from the KDL config (multiple lines, count set by the config):
/// OSC133A + line content. For the instant header only (engine has not spawned the shell and
/// no placeholder exists yet); the normal prompt cycle goes through "placeholder first +
/// redraw_header_cfg fill-in" instead. Returns each line's display width.
pub fn render_header_cfg(
    out: &mut dyn Write,
    cols: usize,
    config: &crate::config::Config,
    info: &HeaderInfo,
    vcs: Option<&GitStatus>,
) -> io::Result<Vec<usize>> {
    prompt_start(out)?;
    let lines = crate::render::render_header_lines(config, info, vcs, cols);
    header_body(out, &lines)
}

/// Fill in/redraw the header: save the input line cursor, move up to header line 1, redraw
/// line by line, restore. The number of rows moved up equals the configured header line count;
/// the input line is untouched. Under the placeholder protocol the shell has already rendered
/// that many blank placeholder lines, so the real content is written over them, and `\x1b8`
/// returns to the input line cursor. Resize redraws and the first fill-in after the `p`
/// announcement share this code.
///
/// Cursor save/restore uses the 7-bit `ESC 7` / `ESC 8` form of DECSC/DECRC rather than the
/// `CSI s` / `CSI u` aliases: nvim's built-in terminal (libvterm) implements only the 7-bit
/// form, so with the aliases the restore lands in the top-left corner and the whole prompt
/// window is painted on the wrong rows.
pub fn redraw_header_cfg(
    out: &mut dyn Write,
    cols: usize,
    config: &crate::config::Config,
    info: &HeaderInfo,
    vcs: Option<&GitStatus>,
) -> io::Result<()> {
    let lines = crate::render::render_header_lines(config, info, vcs, cols);
    let n = lines.len().max(1);
    write!(out, "\x1b7\x1b[{}A", n)?;
    header_body(out, &lines)?;
    write!(out, "\x1b8")?;
    Ok(())
}

/// Overwrite the placeholder prompt: save the cursor, `\r` back to the start of the input line
/// to draw `prefix`, restore the cursor.
///
/// Triggered by the `p` announcement (zle-line-init) — zle has finished rendering the
/// placeholder prompt and the cursor sits after the placeholder. `\e7` saves the cursor, `\r`
/// returns to column 0 to overwrite the placeholder characters column by column, and `\e8`
/// restores the cursor. The prefix covers only the placeholder's columns; when the buffer is
/// non-empty (redraw after resize) the cursor is restored to the end of the buffer, so it never
/// conflicts with zle's cursor model.
pub fn render_prompt(out: &mut dyn Write, prefix: &str) -> io::Result<()> {
    write!(out, "\x1b7\r{prefix}\x1b8")?;
    // OSC 133 B: prompt end marker, telling the terminal the cursor now rests at the input
    // position, so closing the window no longer asks to confirm a "running program" (aligns
    // with p10k _p9k_prompt_suffix).
    write!(out, "\x1b]133;B\x07")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_prompt_starts_with_cr() {
        let mut out = Vec::new();
        render_prompt(&mut out, "❯ ").unwrap();
        let s = String::from_utf8_lossy(&out);
        assert!(
            s.starts_with("\x1b7\r❯ "),
            "should save the cursor, go back to column 0 to draw the prefix over the placeholder, then restore the cursor"
        );
        assert!(
            s.ends_with("\x1b]133;B\x07"),
            "should end with the OSC 133 B marker (telling the terminal the prompt is ready)"
        );
    }
}
