# zsh/default-config.zsh —— 无 ~/.p10k.zsh 时的内置默认配置。
# 风格对齐 p10k 的 lean 预设（简化版，与主题支持的段对应）。

# ── 布局 ──
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs virtualenv time)

# ── 颜色（dark 方案）──
POWERLEVEL9K_COLOR_SCHEME='dark'
POWERLEVEL9K_OS_ICON_BACKGROUND='236'
POWERLEVEL9K_OS_ICON_FOREGROUND='255'
POWERLEVEL9K_DIR_BACKGROUND='blue'
POWERLEVEL9K_DIR_FOREGROUND='236'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='236'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='236'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='magenta'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='236'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='red'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='236'
POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=''
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND='green'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='red'
POWERLEVEL9K_CONTEXT_BACKGROUND='238'
POWERLEVEL9K_CONTEXT_FOREGROUND='255'
POWERLEVEL9K_TIME_BACKGROUND='234'
POWERLEVEL9K_TIME_FOREGROUND='244'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='236'
POWERLEVEL9K_VIRTUALENV_FOREGROUND='255'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='yellow'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='236'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='yellow'
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='236'

# ── 内容模板 ──
POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=''
POWERLEVEL9K_DIR_ICON=''
POWERLEVEL9K_DIR_CONTENT_EXPANSION='%1~'
POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='❯'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='❯'
POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'
POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=''
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION='🐍'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION=''
POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION=''

# ── 布局与分隔符 ──
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
POWERLEVEL9K_LEFT_PROMPT_SEGMENT_END_SYMBOL=' '
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
POWERLEVEL9K_PROMPT_ADD_NEWLINE='true'
POWERLEVEL9K_PROMPT_ADD_NEWLINE_PREFIX=''
POWERLEVEL9K_PROMPT_ADD_NEWLINE_SUFFIX=''

# ── 其他 ──
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD='3'
DEFAULT_USER=''
